version: '3'
services:
  app:
    container_name: openalgo-container
    build: .
    command: python app.py
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/db  # Mount volume to store the SQLite database file persistently
    restart: always

volumes:
  sqlite-data:
    driver: local
